### ISSUE TITLE
iraf-all fails to install on Ubuntu 17.10

### ISSUE THREAD

**Issue by mboquien** [jehturner/astroconda-utils#4]
Hello,

I have been trying to install astroconda but the installation of iraf-all fails for all packages that need some post-processing. It appears that the issue is that ac_config_iraf_pkg hardcodes /usr/bin/python (line 71) but Ubuntu 17.10 does not provide a generic /usr/bin/python file. Changing /usr/bin/python to "env python" in the script solved the issue.

Thanks!

Médéric

**Comment by mboquien** [comment]
I would like to mention that the bug is still present with the latest version. /usr/bin/python is not always python 2.7 and does not even correspond to the Anaconda python. Using “env python” solves the issue.

**Comment by jehturner** [comment]
Sorry, I hadn't seen your first post. Thanks for reporting this problem on Ubuntu.

I think we deliberately avoided using `env` because `conda-build` insists on changing that to point to the conda environment's Python after build time, which is not the intended behaviour. In particular, the conda documentation says that (for better or worse) "post-link" hooks should _"not depend on any installed or to be installed conda packages"_ (ie. it's not guaranteed to work). I believe the rationale for specifying `/usr/bin/python` was that it's [required by the LSB](https://refspecs.linuxfoundation.org/LSB_5.0.0/LSB-Languages/LSB-Languages/pylocation.html) to be in that location (and is also available there on MacOS). Python is a pretty standard part of the OS nowadays, the same as tools like awk or sed... It's too bad that Debian has broken with this convention (especially when they could just have added a symlink), but I expect we can work around it with some additional hack or other :roll_eyes:. I have been meaning to talk to Anaconda about their post-link scheme being too inflexible anyway and maybe this is the occasion.

Thanks!

James.

cc: @jhunkeler, @rendinam

PS. It shouldn't be a problem if it's not Python 2.

**Comment by jehturner** [comment]
On refreshing my memory a bit more, we could probably just look in `/bin/` (or wherever) if python isn't found in `/usr/bin/`, since we already execute the python script via a shell script. Could you confirm the path to your OS python interpreter, please? Are you seeing `ERROR: failed to update extern.pkg for $name` when it doesn't work? Would you be willing to re-check a new build at some point? Thanks.

**Comment by mboquien** [comment]
Thanks for your answer!

I think one of the issues is also that on some distributions /usr/bin/python can point to python 3 (e.g., Arch which I am using at the moment) and the script may not be compatible with python 3 (though I have not checked). Some distributions are actively working towards completely getting rid of python 2, so the problem is bound to become more widespread when this happens. I will try to remember to check on the students' Ubuntu this week.

As for the error, this is indeed what I got when I tried. I am more than happy to try new builds.

**Comment by jehturner** [comment]
Thanks. I believe this particular script ~is working on Python 3 (let me know if it doesn't) and~ is our only dependence on the OS Python.

I'm curious about the software you're teaching to Chilean students. Some of us were looking into the possibility of hosting a Python in Astronomy meeting in Chile at some point, though they decided on a different venue for next year.

**Comment by mboquien** [comment]
I have tried running it with the system's /usr/bin/python (3.7) and I get the following error:

/usr/bin/python iraf.ctio-2010_11_18-1/bin/ac_update_extern_pkg iraf.ctio-2010_11_18-1 ctio
Traceback (most recent call last):
  File "/usr/lib/python3.7/sre_parse.py", line 1021, in parse_template
    this = chr(ESCAPES[this][1])
KeyError: '\\s'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "iraf.ctio-2010_11_18-1/bin/ac_update_extern_pkg", line 111, in <module>
    template_re = re.compile(cat_re, flags=re.M).sub(match_fn, tempbuf)
  File "iraf.ctio-2010_11_18-1/bin/ac_update_extern_pkg", line 107, in match_fn
    return re.sub(sub_re, sub, match.group())    # do & return the substitution
  File "/usr/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/usr/lib/python3.7/re.py", line 309, in _subx
    template = _compile_repl(template, pattern)
  File "/usr/lib/python3.7/re.py", line 300, in _compile_repl
    return sre_parse.parse_template(repl, pattern)
  File "/usr/lib/python3.7/sre_parse.py", line 1024, in parse_template
    raise s.error('bad escape %s' % this, len(this))
re.error: bad escape \s at position 0

If I run it with python 2 (either system or anaconda), it completes without complaining.

As for students, this is a general “Computing for astronomers” for our Master's degree. There is a bit of IRAF (hence this report) but the majority of it is Python with a sprinkle of bash and C++.

I went to the 2016 Python in Astronomy meeting in Seattle and afterwards tried to see whether ESO would be interested in hosting but never got any answer from them at the time. I would be happy to try again. Let me know if I can be of any help.

**Comment by jehturner** [comment]
OK, thanks; I'll need to look into that (I thought I had checked it but might be mixing things up).

Yes, Seattle was also the last one I went to in person. Maybe I'll ping you when I see further discussion re. another year.

**Comment by jehturner** [comment]
Hi Médéric,

Sorry this has sat open for such a long time. I have some new package builds that should resolve this problem. If you get a chance, it would be helpful if you can add the channel http://astroconda.gemini.edu/testing, try installing the packages into some test env again and let us know how it goes. You might want to remove that channel afterwards so you don't pick up test versions in future. Thanks a lot.

James.
